import { Boat } from "./types";

export const mockBoats: Boat[] = [
  {
    id: "BOAT-001",
    name: "Sea Explorer",
    registrationNumber: "EG-2024-001",
    captainName: "Ahmed Hassan",
    capacity: 150,
    boxSize: "20kg",
    status: "active",
    photo: "/placeholder.svg?height=100&width=100",
    lastMaintenanceDate: "2024-01-10",
    currentUtilization: 85,
    totalBoxesUsed: 128,
  },
  {
    id: "BOAT-002",
    name: "Ocean Breeze",
    registrationNumber: "EG-2024-002",
    captainName: "Mohamed Ali",
    capacity: 200,
    boxSize: "25kg",
    status: "active",
    photo: "/placeholder.svg?height=100&width=100",
    lastMaintenanceDate: "2024-01-05",
    currentUtilization: 60,
    totalBoxesUsed: 120,
  },
  {
    id: "BOAT-003",
    name: "Blue Wave",
    registrationNumber: "EG-2024-003",
    captainName: "Omar Mahmoud",
    capacity: 100,
    boxSize: "20kg",
    status: "maintenance",
    photo: "/placeholder.svg?height=100&width=100",
    lastMaintenanceDate: "2024-01-15",
    currentUtilization: 0,
    totalBoxesUsed: 0,
  },
  {
    id: "BOAT-004",
    name: "Coral Reef",
    registrationNumber: "EG-2024-004",
    captainName: "Fatma Omar",
    capacity: 175,
    boxSize: "25kg",
    status: "retired",
    photo: "/placeholder.svg?height=100&width=100",
    lastMaintenanceDate: "2023-12-20",
    currentUtilization: 0,
    totalBoxesUsed: 0,
  },
];
